# Generated by Django 4.2.11 on 2024-03-21 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0005_blogpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
