# Generated by Django 4.2.11 on 2024-03-21 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0006_delete_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
